# Generated by Django 4.1.4 on 2022-12-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('custom_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RouteError',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('custom_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='routelsabinding',
            name='corresponding_constellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='composer.constellation'),
        ),
        migrations.AddField(
            model_name='routelsabinding',
            name='corresponding_route_error',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='composer.routeerror'),
        ),
    ]
