# Generated by Django 3.2.10 on 2021-12-08 08:48

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        # See https://docs.djangoproject.com/en/3.2/ref/contrib/gis/install/postgis/
        CreateExtension('postgis'),
    ]
