# Generated by Django 4.0.1 on 2022-01-04 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routing', '0001_load_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSA',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ingress_geometry', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('egress_geometry', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='LSAMetadata',
            fields=[
                ('lsa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='routing.lsa')),
                ('topic', models.TextField()),
                ('asset_id', models.TextField()),
                ('lane_type', models.TextField()),
                ('language', models.TextField()),
                ('owner_thing', models.TextField()),
                ('info_last_update', models.DateTimeField()),
                ('connection_id', models.CharField(max_length=10)),
                ('egress_lane_id', models.CharField(max_length=10)),
                ('ingress_lane_id', models.CharField(max_length=10)),
                ('traffic_lights_id', models.CharField(max_length=10)),
                ('signal_group_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LSACell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('hex', models.CharField(max_length=15)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('lsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='routing.lsa')),
            ],
        ),
    ]
