# Generated by Django 4.0.4 on 2022-05-12 14:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routing', '0001_load_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SG',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ingress_geometry', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('egress_geometry', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SGMetadata',
            fields=[
                ('sg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='routing.sg')),
                ('topic', models.TextField()),
                ('asset_id', models.TextField()),
                ('lane_type', models.TextField()),
                ('language', models.TextField()),
                ('owner_thing', models.TextField()),
                ('info_last_update', models.DateTimeField()),
                ('connection_id', models.CharField(max_length=10)),
                ('egress_lane_id', models.CharField(max_length=10)),
                ('ingress_lane_id', models.CharField(max_length=10)),
                ('traffic_lights_id', models.CharField(max_length=10)),
                ('signal_group_id', models.CharField(max_length=25)),
            ],
        ),
    ]
