# Generated by Django 4.0.4 on 2022-04-29 13:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routing', '0001_load_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalGroup',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
            ],
        ),
    ]
