# Generated by Django 4.1 on 2022-10-05 08:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_lsa_md5'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSACrossing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('connected', models.BooleanField(default=False)),
            ],
        ),
    ]
