# Generated by Django 4.1.2 on 2022-10-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_lsacrossing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsa',
            name='md5',
        ),
        migrations.DeleteModel(
            name='LSACell',
        ),
    ]
