# Generated by Django 4.2.8 on 2023-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0007_planetosmline'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsa',
            name='bearing',
            field=models.FloatField(default=None, null=True),
        ),
    ]
